package server

import (
	"testing"

	"github.com/tenntenn/sbnn/internal/diff"
	"github.com/tenntenn/sbnn/internal/model"
)

// What counts as a file declaring itself generated. Everything here is the
// file speaking: a generator wrote the line so tools would leave it alone.
// Anything else - a big file, a name that looks generated, a vendor
// directory - is sbnn guessing, and a wrong guess folds code nobody then
// reads.
func TestGeneratedMarkerIsASelfDeclaration(t *testing.T) {
	declares := []string{
		"// Code generated by protoc-gen-go. DO NOT EDIT.",
		"# Code generated by mockery v2. DO NOT EDIT.",
		"/* @generated */",
		" * @generated by some tool",
		"<!-- Automatically generated, do not edit -->",
		"// DO NOT EDIT. This file was generated.",
		"#!/bin/sh\n# generated file - do not modify",
	}
	for _, content := range declares {
		if diff.GeneratedMarker(content) == "" {
			t.Errorf("should be taken as generated: %q", content)
		}
	}

	// None of these say anything about being generated, however big, ugly
	// or machine-ish they look.
	silent := []string{
		"package main",
		"{\n  \"lockfileVersion\": 3,\n  \"packages\": {}\n}",
		"// This file generates the parser tables.",
		"// Edit with care: the generator downstream depends on this shape.",
		"var minified=function(a,b){return a+b}",
		"",
	}
	for _, content := range silent {
		if got := diff.GeneratedMarker(content); got != "" {
			t.Errorf("should be left alone: %q matched %q", content, got)
		}
	}

	// A declaration far down a file is not a declaration anybody reads.
	deep := "package main\n\n\n\n\n\n\n\n\n\n\n// Code generated by x. DO NOT EDIT."
	if got := diff.GeneratedMarker(deep); got != "" {
		t.Errorf("a marker on line 12 should not count, got %q", got)
	}
}

// A unified diff usually does not carry the top of a modified file. That
// absence says nothing, so nothing is folded on it.
func TestVisibleTopOnlyWhenTheDiffReachesTheTop(t *testing.T) {
	top := &model.File{Hunks: []*model.Hunk{{NewStart: 1, Lines: []model.Line{
		{Kind: model.LineContext, Content: "// Code generated by x. DO NOT EDIT."},
		{Kind: model.LineAdd, Content: "var a = 1"},
	}}}}
	if diff.GeneratedMarker(diff.VisibleTop(top)) == "" {
		t.Error("a hunk starting at line 1 shows the declaration")
	}

	middle := &model.File{Hunks: []*model.Hunk{{NewStart: 200, Lines: []model.Line{
		{Kind: model.LineAdd, Content: "// Code generated by x. DO NOT EDIT."},
	}}}}
	if got := diff.VisibleTop(middle); got != "" {
		t.Errorf("a hunk at line 200 is not the top of the file, got %q", got)
	}
}

// The patterns the sender passes, matched the way .gitignore taught
// everyone to expect.
func TestCollapsePatterns(t *testing.T) {
	cases := []struct {
		pattern string
		path    string
		want    bool
	}{
		{"go.sum", "go.sum", true},
		{"go.sum", "sub/module/go.sum", true}, // no slash: the name, at any depth
		{"go.sum", "go.sum.bak", false},       // and the whole name, not a prefix
		{"*.lock", "web/pnpm.lock", true},
		{"web/dist/**", "web/dist/assets/x.js", true},
		{"web/dist/**", "web/dist/index.html", true},
		{"web/dist/**", "web/src/index.ts", false},
		{"**/*.pb.go", "internal/api/user.pb.go", true},
		{"**/*.pb.go", "user.pb.go", true},
		{"internal/*.go", "internal/a.go", true},
		{"internal/*.go", "internal/deep/a.go", false}, // one star, one level
		{"", "anything", false},

		// issue #18: patterns with two or more "**"
		{"**/testdata/**", "a/b/testdata/c/d.txt", true},
		{"**/node_modules/**", "web/node_modules/x/y.js", true},
		{"**/testdata/**", "testdata/a.txt", true},     // a leading ** spans no directory too
		{"**/testdata/**", "a/b/testdata", false},      // the directory itself is not its contents
		{"**/testdata/**", "a/testdataX/c.txt", false}, // and a segment matches whole, not in part
		{"a/**/b/**/c.txt", "a/x/y/b/z/c.txt", true},   // two **, one in the middle
		{"a/**/b/**/c.txt", "a/x/y/c.txt", false},      // the b in between is missing
		{"**", "anything/at/all.txt", true},
		{"**/x", "a/b/x", true},
	}
	for _, tc := range cases {
		if _, got := matchAny([]string{tc.pattern}, tc.path); got != tc.want {
			t.Errorf("pattern %q against %q = %v, want %v", tc.pattern, tc.path, got, tc.want)
		}
	}
}

// Folding says why, every time, and folds nothing it cannot explain.
func TestFoldFilesAlwaysGivesAReason(t *testing.T) {
	d := &model.Diff{Files: []*model.File{
		{NewPath: "go.sum", Hunks: []*model.Hunk{{NewStart: 1, Lines: []model.Line{
			{Kind: model.LineAdd, Content: "example.com/x v1.0.0 h1:abc="},
		}}}},
		{NewPath: "api.pb.go", Hunks: []*model.Hunk{{NewStart: 1, Lines: []model.Line{
			{Kind: model.LineContext, Content: "// Code generated by protoc-gen-go. DO NOT EDIT."},
		}}}},
		{NewPath: "main.go", Hunks: []*model.Hunk{{NewStart: 1, Lines: []model.Line{
			{Kind: model.LineAdd, Content: "package main"},
		}}}},
	}}
	foldFiles(d, []string{"go.sum"})

	if !d.Files[0].Folded || d.Files[0].FoldReason == "" {
		t.Errorf("go.sum: %+v", d.Files[0])
	}
	if !d.Files[1].Folded || d.Files[1].FoldReason == "" {
		t.Errorf("api.pb.go: %+v", d.Files[1])
	}
	if d.Files[2].Folded {
		t.Errorf("main.go was folded for no reason: %+v", d.Files[2])
	}
	for _, f := range d.Files {
		if f.Folded && f.FoldReason == "" {
			t.Errorf("%s was folded without saying why", f.Path())
		}
	}
}
