package server

import (
	"strings"
	"testing"
	"unicode/utf8"

	"github.com/tenntenn/sbnn/internal/diff"
	"github.com/tenntenn/sbnn/internal/model"
)

// What counts as a file declaring itself generated. Everything here is the
// file speaking: a generator wrote the line so tools would leave it alone.
// Anything else - a big file, a name that looks generated, a vendor
// directory - is sbnn guessing, and a wrong guess folds code nobody then
// reads.
func TestGeneratedMarkerIsASelfDeclaration(t *testing.T) {
	declares := []string{
		"// Code generated by protoc-gen-go. DO NOT EDIT.",
		"# Code generated by mockery v2. DO NOT EDIT.",
		"/* @generated */",
		" * @generated by some tool",
		"<!-- Automatically generated, do not edit -->",
		"// DO NOT EDIT. This file was generated.",
		"#!/bin/sh\n# generated file - do not modify",
	}
	for _, content := range declares {
		if diff.GeneratedMarker(content) == "" {
			t.Errorf("should be taken as generated: %q", content)
		}
	}

	// None of these say anything about being generated, however big, ugly
	// or machine-ish they look.
	silent := []string{
		"package main",
		"{\n  \"lockfileVersion\": 3,\n  \"packages\": {}\n}",
		"// This file generates the parser tables.",
		"// Edit with care: the generator downstream depends on this shape.",
		"var minified=function(a,b){return a+b}",
		"",
	}
	for _, content := range silent {
		if got := diff.GeneratedMarker(content); got != "" {
			t.Errorf("should be left alone: %q matched %q", content, got)
		}
	}

	// A declaration far down a file is not a declaration anybody reads.
	deep := "package main\n\n\n\n\n\n\n\n\n\n\n// Code generated by x. DO NOT EDIT."
	if got := diff.GeneratedMarker(deep); got != "" {
		t.Errorf("a marker on line 12 should not count, got %q", got)
	}
}

// A unified diff usually does not carry the top of a modified file. That
// absence says nothing, so nothing is folded on it.
func TestVisibleTopOnlyWhenTheDiffReachesTheTop(t *testing.T) {
	top := &model.File{Hunks: []*model.Hunk{{NewStart: 1, Lines: []model.Line{
		{Kind: model.LineContext, Content: "// Code generated by x. DO NOT EDIT."},
		{Kind: model.LineAdd, Content: "var a = 1"},
	}}}}
	if diff.GeneratedMarker(diff.VisibleTop(top)) == "" {
		t.Error("a hunk starting at line 1 shows the declaration")
	}

	middle := &model.File{Hunks: []*model.Hunk{{NewStart: 200, Lines: []model.Line{
		{Kind: model.LineAdd, Content: "// Code generated by x. DO NOT EDIT."},
	}}}}
	if got := diff.VisibleTop(middle); got != "" {
		t.Errorf("a hunk at line 200 is not the top of the file, got %q", got)
	}
}

// The patterns the sender passes, matched the way .gitignore taught
// everyone to expect.
func TestCollapsePatterns(t *testing.T) {
	cases := []struct {
		pattern string
		path    string
		want    bool
	}{
		{"go.sum", "go.sum", true},
		{"go.sum", "sub/module/go.sum", true}, // no slash: the name, at any depth
		{"go.sum", "go.sum.bak", false},       // and the whole name, not a prefix
		{"*.lock", "web/pnpm.lock", true},
		{"web/dist/**", "web/dist/assets/x.js", true},
		{"web/dist/**", "web/dist/index.html", true},
		{"web/dist/**", "web/src/index.ts", false},
		{"**/*.pb.go", "internal/api/user.pb.go", true},
		{"**/*.pb.go", "user.pb.go", true},
		{"internal/*.go", "internal/a.go", true},
		{"internal/*.go", "internal/deep/a.go", false}, // one star, one level
		{"", "anything", false},
	}
	for _, tc := range cases {
		if _, got := matchAny([]string{tc.pattern}, tc.path); got != tc.want {
			t.Errorf("pattern %q against %q = %v, want %v", tc.pattern, tc.path, got, tc.want)
		}
	}
}

// Folding says why, every time, and folds nothing it cannot explain.
func TestFoldFilesAlwaysGivesAReason(t *testing.T) {
	d := &model.Diff{Files: []*model.File{
		{NewPath: "go.sum", Hunks: []*model.Hunk{{NewStart: 1, Lines: []model.Line{
			{Kind: model.LineAdd, Content: "example.com/x v1.0.0 h1:abc="},
		}}}},
		{NewPath: "api.pb.go", Hunks: []*model.Hunk{{NewStart: 1, Lines: []model.Line{
			{Kind: model.LineContext, Content: "// Code generated by protoc-gen-go. DO NOT EDIT."},
		}}}},
		{NewPath: "main.go", Hunks: []*model.Hunk{{NewStart: 1, Lines: []model.Line{
			{Kind: model.LineAdd, Content: "package main"},
		}}}},
	}}
	foldFiles(d, []string{"go.sum"})

	if !d.Files[0].Folded || d.Files[0].FoldReason == "" {
		t.Errorf("go.sum: %+v", d.Files[0])
	}
	if !d.Files[1].Folded || d.Files[1].FoldReason == "" {
		t.Errorf("api.pb.go: %+v", d.Files[1])
	}
	if d.Files[2].Folded {
		t.Errorf("main.go was folded for no reason: %+v", d.Files[2])
	}
	for _, f := range d.Files {
		if f.Folded && f.FoldReason == "" {
			t.Errorf("%s was folded without saying why", f.Path())
		}
	}
}

// A fold reason is text somebody reads, so it is cut where text can be cut.
// shorten counts runes: cutting 60 bytes into Japanese lands in the middle
// of a rune, and the broken bytes reach the browser as U+FFFD.
func TestShortenKeepsRunesWhole(t *testing.T) {
	// The marker from the issue: 118 bytes, but only 43 runes. Counted in
	// bytes it was cut at 60 and came apart mid-rune; counted in runes it
	// fits under the 60 foldFiles passes, and is left whole.
	s := "// 自動生成されたファイルです。編集しないでください。これは非常に長いマーカー行です"
	got := shorten(s, 60)
	if !utf8.ValidString(got) {
		t.Errorf("cut mid-rune: %q", got)
	}
	if got != s {
		t.Errorf("shorten(%q, 60) = %q, want it whole: 43 runes fit in 60", s, got)
	}

	// Cut the same text where it really is too long, and the cut lands on a
	// rune boundary and costs exactly the runes it says.
	cut := shorten(s, 20)
	if !utf8.ValidString(cut) {
		t.Errorf("cut mid-rune: %q", cut)
	}
	if n := utf8.RuneCountInString(cut); n != 20 {
		t.Errorf("shorten(%q, 20) is %d runes, want 20: %q", s, n, cut)
	}
	if !strings.HasSuffix(cut, "…") {
		t.Errorf("a cut string says it was cut, got %q", cut)
	}

	// The ASCII case the byte slicing already got right, unchanged.
	if got, want := shorten(strings.Repeat("a", 100), 10), "aaaaaaaaa…"; got != want {
		t.Errorf("shorten(100 a's, 10) = %q, want %q", got, want)
	}
	if n := utf8.RuneCountInString(shorten(strings.Repeat("a", 100), 10)); n != 10 {
		t.Errorf("shorten(100 a's, 10) is %d runes, want 10", n)
	}

	// Nothing that fits is touched - no cut, no ellipsis - and that holds
	// right up to the last rune that fits.
	for _, tc := range []struct {
		s    string
		n    int
		want string
	}{
		{"short enough", 60, "short enough"},
		{"あいうえお", 60, "あいうえお"},
		{"あいうえお", 5, "あいうえお"}, // exactly n runes: still whole
		{strings.Repeat("a", 10), 10, strings.Repeat("a", 10)},
		{"  padded  ", 60, "padded"}, // the surrounding space still goes
		{"  " + strings.Repeat("あ", 8) + "  ", 8, strings.Repeat("あ", 8)},
	} {
		if got := shorten(tc.s, tc.n); got != tc.want {
			t.Errorf("shorten(%q, %d) = %q, want %q", tc.s, tc.n, got, tc.want)
		}
	}

	// Never reached from foldFiles, which passes 60, but a function that
	// panics is not one to leave lying about.
	if got := shorten("あいうえお", 0); got != "" {
		t.Errorf(`shorten("あいうえお", 0) = %q, want ""`, got)
	}
}
