package diff_test

import (
	"strings"
	"testing"

	"github.com/tenntenn/sbnn/internal/diff"
	"github.com/tenntenn/sbnn/internal/model"
)

// A file declares itself generated in whatever language its generator writes
// in. Folding only the English ones would fold a Japanese project's generated
// files just when their header happened to be in English - the same file, the
// same generator, the same intent, a different review.
func TestGeneratedMarkerReadsJapaneseDeclarations(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    string
	}{
		{
			name:    "japanese header",
			content: "// このファイルは自動生成されています。編集しないでください。\npackage main",
			want:    "// このファイルは自動生成されています。編集しないでください。",
		},
		{
			name:    "automatically generated in japanese",
			content: "# このファイルはツールにより自動的に生成されました\nname: ci",
			want:    "# このファイルはツールにより自動的に生成されました",
		},
		{
			name:    "do not edit by hand",
			content: "<!-- 手動で編集しないこと -->\n<html>",
			want:    "<!-- 手動で編集しないこと -->",
		},
		{
			name:    "editing forbidden",
			content: "-- 編集不可: generator が上書きします\nSELECT 1;",
			want:    "-- 編集不可: generator が上書きします",
		},
		{
			name:    "after a shebang and a licence header",
			content: "#!/bin/sh\n# Copyright 2026\n#\n# 自動生成されたファイルです\necho hi",
			want:    "# 自動生成されたファイルです",
		},
		{
			name:    "english still understood",
			content: "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage main",
			want:    "// Code generated by protoc-gen-go. DO NOT EDIT.",
		},
		{
			name:    "mixed header reports the line it found",
			content: "// Code generated by tool. DO NOT EDIT. 編集しないこと\npackage main",
			want:    "// Code generated by tool. DO NOT EDIT. 編集しないこと",
		},
		{
			name:    "japanese prose about generating is not a declaration",
			content: "// トークンを生成する。\n// 生成器はこのファイルを読む。\npackage token",
			want:    "",
		},
		{
			name:    "no declaration at all",
			content: "package main\n\nfunc main() {}",
			want:    "",
		},
		{
			name:    "too far down to be a declaration anybody reads",
			content: strings.Repeat("package main\n", 11) + "// 自動生成されたファイル",
			want:    "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := diff.GeneratedMarker(tt.content); got != tt.want {
				t.Errorf("GeneratedMarker() = %q, want %q", got, tt.want)
			}
		})
	}
}

// Nothing is read from a path or an extension: the answer comes from the
// line the file itself carries, and from nowhere else.
func TestGeneratedMarkerIgnoresEverythingButTheContent(t *testing.T) {
	silent := []string{
		"internal/gen/api.pb.go",
		"vendor/foo/bar.min.js",
		"package main // ここでは自動では生成しない",
	}
	for _, content := range silent {
		if got := diff.GeneratedMarker(content); got != "" {
			t.Errorf("should be left alone: %q matched %q", content, got)
		}
	}
}

// VisibleTop is the only way a declaration is looked for when the file itself
// cannot be read, so it must stop at the top of the new side and nowhere else.
func TestVisibleTopIsTheNewSideOfTheFirstHunk(t *testing.T) {
	tests := []struct {
		name string
		file *model.File
		want string
	}{
		{
			name: "no hunks",
			file: &model.File{},
			want: "",
		},
		{
			name: "first hunk does not start at line 1",
			file: &model.File{Hunks: []*model.Hunk{{NewStart: 12, Lines: []model.Line{
				{Kind: model.LineContext, Content: "// 自動生成"},
			}}}},
			want: "",
		},
		{
			name: "deleted lines are not part of the new side",
			file: &model.File{Hunks: []*model.Hunk{{NewStart: 1, Lines: []model.Line{
				{Kind: model.LineDelete, Content: "// 手で書いたファイル"},
				{Kind: model.LineAdd, Content: "// 自動生成されたファイルです"},
				{Kind: model.LineContext, Content: "package main"},
			}}}},
			want: "// 自動生成されたファイルです\npackage main",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := diff.VisibleTop(tt.file); got != tt.want {
				t.Errorf("VisibleTop() = %q, want %q", got, tt.want)
			}
		})
	}

	// However long the first hunk is, only the top of the file is read.
	long := &model.Hunk{NewStart: 1}
	for i := 0; i < 40; i++ {
		long.Lines = append(long.Lines, model.Line{Kind: model.LineContext, Content: "x"})
	}
	if n := len(strings.Split(diff.VisibleTop(&model.File{Hunks: []*model.Hunk{long}}), "\n")); n != 10 {
		t.Errorf("VisibleTop returned %d lines, want 10", n)
	}
}
