package diff_test

import (
	"strings"
	"testing"

	"github.com/tenntenn/sbnn/internal/diff"
	"github.com/tenntenn/sbnn/internal/model"
)

// A file declares itself generated in whatever language its generator writes
// in. Folding only the English ones would fold a Japanese project's generated
// files just when their header happened to be in English - the same file, the
// same generator, the same intent, a different review.
func TestGeneratedMarkerReadsJapaneseDeclarations(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    string
	}{
		{
			name:    "japanese header",
			content: "// このファイルは自動生成されています。編集しないでください。\npackage main",
			want:    "// このファイルは自動生成されています。編集しないでください。",
		},
		{
			name:    "automatically generated in japanese",
			content: "# このファイルはツールにより自動的に生成されました\nname: ci",
			want:    "# このファイルはツールにより自動的に生成されました",
		},
		{
			// "Do not edit" on its own says nothing about where the file
			// came from, and the English side has never matched it either
			// - "<!-- do not edit by hand -->" is not a declaration there
			// and is not one here. A file that only says this is left to
			// the reader, the same in both languages.
			name:    "do not edit, with no word about being generated, is not a declaration",
			content: "<!-- 手動で編集しないこと -->\n<html>",
			want:    "",
		},
		{
			name:    "the english equivalent is not one either",
			content: "<!-- do not edit by hand -->\n<html>",
			want:    "",
		},
		{
			name:    "both halves, in the other order",
			content: "<!-- 編集しないでください。自動生成されます。 -->\n<html>",
			want:    "<!-- 編集しないでください。自動生成されます。 -->",
		},
		{
			name:    "a generated file that says so as its predicate",
			content: "-- 自動生成されたファイルです\nSELECT 1;",
			want:    "-- 自動生成されたファイルです",
		},
		{
			name:    "editing forbidden",
			content: "-- 編集不可: generator が上書きします\nSELECT 1;",
			want:    "-- 編集不可: generator が上書きします",
		},
		{
			name:    "after a shebang and a licence header",
			content: "#!/bin/sh\n# Copyright 2026\n#\n# 自動生成されたファイルです\necho hi",
			want:    "# 自動生成されたファイルです",
		},
		{
			name:    "english still understood",
			content: "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage main",
			want:    "// Code generated by protoc-gen-go. DO NOT EDIT.",
		},
		{
			name:    "mixed header reports the line it found",
			content: "// Code generated by tool. DO NOT EDIT. 編集しないこと\npackage main",
			want:    "// Code generated by tool. DO NOT EDIT. 編集しないこと",
		},
		{
			name:    "japanese prose about generating is not a declaration",
			content: "// トークンを生成する。\n// 生成器はこのファイルを読む。\npackage token",
			want:    "",
		},
		{
			name:    "no declaration at all",
			content: "package main\n\nfunc main() {}",
			want:    "",
		},
		{
			name:    "too far down to be a declaration anybody reads",
			content: strings.Repeat("package main\n", 11) + "// 自動生成されたファイル",
			want:    "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := diff.GeneratedMarker(tt.content); got != tt.want {
				t.Errorf("GeneratedMarker() = %q, want %q", got, tt.want)
			}
		})
	}
}

// Nothing is read from a path or an extension: the answer comes from the
// line the file itself carries, and from nowhere else.
func TestGeneratedMarkerIgnoresEverythingButTheContent(t *testing.T) {
	silent := []string{
		"internal/gen/api.pb.go",
		"vendor/foo/bar.min.js",
		"package main // ここでは自動では生成しない",
	}
	for _, content := range silent {
		if got := diff.GeneratedMarker(content); got != "" {
			t.Errorf("should be left alone: %q matched %q", content, got)
		}
	}
}

// VisibleTop is the only way a declaration is looked for when the file itself
// cannot be read, so it must stop at the top of the new side and nowhere else.
func TestVisibleTopIsTheNewSideOfTheFirstHunk(t *testing.T) {
	tests := []struct {
		name string
		file *model.File
		want string
	}{
		{
			name: "no hunks",
			file: &model.File{},
			want: "",
		},
		{
			name: "first hunk does not start at line 1",
			file: &model.File{Hunks: []*model.Hunk{{NewStart: 12, Lines: []model.Line{
				{Kind: model.LineContext, Content: "// 自動生成"},
			}}}},
			want: "",
		},
		{
			name: "deleted lines are not part of the new side",
			file: &model.File{Hunks: []*model.Hunk{{NewStart: 1, Lines: []model.Line{
				{Kind: model.LineDelete, Content: "// 手で書いたファイル"},
				{Kind: model.LineAdd, Content: "// 自動生成されたファイルです"},
				{Kind: model.LineContext, Content: "package main"},
			}}}},
			want: "// 自動生成されたファイルです\npackage main",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := diff.VisibleTop(tt.file); got != tt.want {
				t.Errorf("VisibleTop() = %q, want %q", got, tt.want)
			}
		})
	}

	// However long the first hunk is, only the top of the file is read.
	long := &model.Hunk{NewStart: 1}
	for i := 0; i < 40; i++ {
		long.Lines = append(long.Lines, model.Line{Kind: model.LineContext, Content: "x"})
	}
	if n := len(strings.Split(diff.VisibleTop(&model.File{Hunks: []*model.Hunk{long}}), "\n")); n != 10 {
		t.Errorf("VisibleTop returned %d lines, want 10", n)
	}
}

// Every one of these is hand-written Japanese that mentions generating or
// editing, and folding any of them would hide code from a review. They are
// the reason the two halves of a declaration are required together: the
// English patterns have always wanted "generated" *and* "do not edit", and
// a Japanese file gets the same reading rather than a looser one.
func TestGeneratedMarkerDoesNotFoldJapanesePros(t *testing.T) {
	for _, tt := range []struct {
		name string
		line string
	}{
		{"a package saying what it generates", "// Package gen はテンプレートから Go のコードを自動生成する。"},
		{"a comment about generated code", "// 自動生成されたコードが正しいかを検証する。"},
		{"a UI label", "\tLabelReadOnly = \"編集不可\""},
		{"a changelog entry", "- 自動生成のロジックを見直した"},
		{"documentation saying the opposite", "設定ファイルは自動生成されません。手で書いてください。"},
		{"a translation string", "\t\"locked\": \"編集しないでください\","},
		{"a step in a how-to", "1. 自動生成を有効にする"},
		{"a generator talking about its own output", "// このファイルの生成ロジックを見直す"},
		{"this file as an object, not the subject", "// 生成器はこのファイルを読む。"},
	} {
		t.Run(tt.name, func(t *testing.T) {
			if got := diff.GeneratedMarker(tt.line); got != "" {
				t.Errorf("GeneratedMarker(%q) = %q, want \"\" - it is hand-written", tt.line, got)
			}
		})
	}
}

// The English half of the same asymmetry: none of these is a declaration
// either, so the Japanese ones above are not being held to a stricter rule.
func TestGeneratedMarkerDoesNotFoldEnglishProse(t *testing.T) {
	for _, line := range []string{
		"// Package gen generates Go code from templates.",
		"// Verifies that generated code is correct.",
		"- reworked the code generation logic",
		"\tLabelReadOnly = \"read only\"",
	} {
		if got := diff.GeneratedMarker(line); got != "" {
			t.Errorf("GeneratedMarker(%q) = %q, want \"\"", line, got)
		}
	}
}
