import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { foldLabel } from '../src/foldLabel'

// The server writes foldReason itself; these are the two it writes.
const collapsed = 'the sender asked for it (--collapse go.sum)'
const generated = 'the file says so: // Code generated by protoc-gen-go. DO NOT EDIT.'

describe('foldLabel', () => {
  // The bug: the label defaulted to "the sender asked for it" whenever
  // foldReason was empty, so a file the reader folded with the header button
  // or `f` told them the sender had asked for it. Inventing a reason for a
  // fold the reader performed is the one claim the fold design refuses to
  // make.
  it('does not credit the sender for a fold the reader performed', () => {
    const got = foldLabel(true, undefined)
    assert.equal(got, 'Folded by you')
    assert.ok(!got.includes('the sender asked for it'))
  })

  it('gives the sender their reason when the sender folded it', () => {
    assert.equal(foldLabel(false, collapsed), `Folded — ${collapsed}`)
    assert.equal(foldLabel(false, generated), `Folded — ${generated}`)
  })

  // A file the sender folded can be opened by the reader and folded again by
  // hand. Both are then true, and the reason is the one fact the reader
  // cannot recover from the page, so it stays.
  it('keeps the sender reason when the reader folds an already-folded file', () => {
    const got = foldLabel(true, collapsed)
    assert.ok(got.includes(collapsed))
    assert.ok(got.includes('you'))
    assert.equal(got, `Folded by you — the sender had folded it too: ${collapsed}`)
  })

  // Should not arise: sbnn never folds a file on its own without a reason.
  // Say only what is certain rather than guessing at whose fold it is.
  it('says only what is certain when there is neither', () => {
    assert.equal(foldLabel(false, undefined), 'Folded')
    assert.equal(foldLabel(false, ''), 'Folded')
  })

  it('treats an empty reason as no reason', () => {
    assert.equal(foldLabel(true, ''), 'Folded by you')
  })
})
